name: "❓ Ask for help"
description: "Submit any question related to Uptime Kuma"
title: "[Help]: <title>"
labels: [help]
body:
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "📝 Describe your problem"
      description: "Please walk us through it step by step."
      placeholder: "Describe what are you asking for..."
  - type: input
    id: uptime-kuma-version
    attributes:
      label: "🐻 Uptime-Kuma version"
      description: "Which version of Uptime-Kuma are you running?"
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: "💻 Operating System"
      description: "Which OS is your server/device running on?"
      multiple: true
      options:
        - Linux
        - MacOS
        - Windows
    validations:
      required: true
  - type: dropdown
    id: browser-vendor
    attributes:
      label: "🌐 Browser"
      description: "Which browser are you running on?"
      multiple: true
      options:
        - Firefox
        - Chrome
        - Edge
        - Safari
        - Other
    validations:
      required: true
  - type: checkboxes
    id: uses-docker
    attributes:
      label: "🐋 Docker"
      options:
        - label: "Currently running in Docker?"
          required: false
    validations:
      required: true
  - type: input
    id: nodejs-version
    attributes:
      label: "🟩 NodeJS Version"
      description: "If running in the host, which version of NodeJS are you running?"
    validations:
      required: false
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you spent some time to check if this question has been raised before?"
      description: "Please search in the issues without filters [here](https://github.com/louislam/uptime-kuma/issues?q=)"
      options:
        - label: "I checked and didn't find similar question"
          required: true
  - type: checkboxes
    attributes:
      label: "🛡️ Security Policy"
      description: Please review the security policy before reporting security related issues/bugs.
      options:
        - label: I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
          required: true
